name: local dev env validation
# for developer local environment script or test usage
on:
  workflow_call:

jobs:
  verify_model_training_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: local script test
        run: cd model_training && ./script.sh prepare_cluster
      - name: clean up
        run: cd model_training && ./script.sh cleanup